version: '3.8'

services:
  frontend:
    image: 825004603200.dkr.ecr.ap-southeast-1.amazonaws.com/sb-production-core-xqv927edyrw7-service1-60noauwuqogs:frontend_tag
    ports:
      - "3000:80"  # Map port 3000 on host to port 80 in container
    depends_on:
      - backend  # Ensure backend starts before frontend

  backend:
    image: 825004603200.dkr.ecr.ap-southeast-1.amazonaws.com/sb-production-core-xqv927edyrw7-service1-60noauwuqogs:backend_tag
    ports:
      - "3001:3001"  # Map port 3001 on host to port 3001 in container
    environment:  # Environment variables for backend
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=your_user
      - DATABASE_PASSWORD=your_password
      - DATABASE_NAME=your_database
    depends_on:
      db:
        condition: service_healthy  # Wait until db is healthy

  db:
    image: postgres:latest  # Use the latest PostgreSQL image
    ports:
      - "5432:5432"  # Map port 5432 on host to port 5432 in container
    environment:  # Environment variables for PostgreSQL
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "your_user"]
      interval: 10s
      timeout: 5s
      retries: 5