version: '3.8'

services:
  frontend:
    image: 825004603200.dkr.ecr.ap-southeast-1.amazonaws.com/sb-production-core-xqv927edyrw7-service1-60noauwuqogs:frontend_tag
    ports:
      - "3000:80"  # Map port 3000 on host to port 80 in container
    depends_on:
      - backend  # Ensure backend starts before frontend

  backend:
    image: 825004603200.dkr.ecr.ap-southeast-1.amazonaws.com/sb-production-core-xqv927edyrw7-service1-60noauwuqogs:backend_tag
    ports:
      - "3001:3001"  # Map port 3001 on host to port 3001 in container
    environment:  # Use environment variables from .env file
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      db:
        condition: service_healthy  # Wait until db is healthy

  db:
    image: postgres:latest  # Use the latest PostgreSQL image
    ports:
      - "5432:5432"  # Map port 5432 on host to port 5432 in container
    environment:  # Use environment variables from .env file
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:  # Add health check for db service
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

