openapi: 3.0.0
info:
  title: KMS API
  version: 1.0.0
paths:
  /canvases:
    get:
      summary: Get all canvases
      responses:
        '200':
          description: A list of canvases
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Canvas'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    post:
      summary: Create a new canvas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCanvasDto'
        required: true
      responses:
        '201':
          description: The created canvas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Canvas'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /canvases/{id}:
    get:
      summary: Get a canvas by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: The canvas ID
      responses:
        '200':
          description: A canvas object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Canvas'
        '401':
          description: Unauthorized
        '404':
          description: Canvas not found
        '500':
          description: Internal Server Error
components:
  schemas:
    Canvas:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        createdAt:
          type: string
          format: date-time
      example:
        id: "1"
        name: "My Canvas"
        createdAt: "2021-01-01T00:00:00.000Z"
    CreateCanvasDto:
      type: object
      properties:
        name:
          type: string
      example:
        name: "New Canvas"
securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT
security:
  - bearerAuth: []
